[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "TeleOCR-vllm"
version = "1.0.0"
description = "Out-of-tree vLLM model plugin for TeleOCR-1B."
requires-python = ">=3.10"
dependencies = [
  "vllm==0.11.0",
  "transformers==4.57.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["TeleOCR_vllm*"]

[project.entry-points."vllm.general_plugins"]
TeleOCR_vllm = "TeleOCR_vllm:register" 
